inherited frmInformarLimiteDistribuidor: TfrmInformarLimiteDistribuidor
  Caption = 'Informar Limite Distribuidor'
  ClientHeight = 169
  ClientWidth = 475
  OnCreate = FormCreate
  ExplicitWidth = 491
  ExplicitHeight = 208
  PixelsPerInch = 96
  TextHeight = 13
  object Label1: TLabel
    Left = 24
    Top = 16
    Width = 66
    Height = 13
    Caption = 'Distribuidor'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Tahoma'
    Font.Style = [fsBold]
    ParentFont = False
  end
  object Label2: TLabel
    Left = 24
    Top = 66
    Width = 35
    Height = 13
    Caption = 'Limite'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Tahoma'
    Font.Style = [fsBold]
    ParentFont = False
  end
  object btnPesquisarDistribuidor: TSpeedButton
    Left = 93
    Top = 31
    Width = 23
    Height = 22
    Caption = '...'
    OnClick = btnPesquisarDistribuidorClick
  end
  object Panel1: TPanel
    Left = 0
    Top = 128
    Width = 475
    Height = 41
    Align = alBottom
    BevelOuter = bvLowered
    TabOrder = 3
    ExplicitTop = 171
    object btnConfirmar: TBitBtn
      Left = 56
      Top = 8
      Width = 75
      Height = 25
      Caption = 'Confirmar'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Tahoma'
      Font.Style = [fsBold]
      ParentFont = False
      TabOrder = 0
      OnClick = btnConfirmarClick
    end
    object btnCancelar: TBitBtn
      Left = 320
      Top = 8
      Width = 75
      Height = 25
      Caption = 'Cancelar'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Tahoma'
      Font.Style = [fsBold]
      ParentFont = False
      TabOrder = 1
      OnClick = btnCancelarClick
    end
  end
  object edtCodigoDistribuidor: TEdit
    Left = 24
    Top = 32
    Width = 66
    Height = 21
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Tahoma'
    Font.Style = [fsBold]
    ParentFont = False
    TabOrder = 0
    OnExit = edtCodigoDistribuidorExit
  end
  object edtNomeDistribuidor: TEdit
    Left = 120
    Top = 32
    Width = 283
    Height = 21
    TabStop = False
    Color = cl3DLight
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Tahoma'
    Font.Style = [fsBold]
    ParentFont = False
    ReadOnly = True
    TabOrder = 1
  end
  object edtLimite: TEdit
    Left = 24
    Top = 82
    Width = 121
    Height = 21
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Tahoma'
    Font.Style = [fsBold]
    ParentFont = False
    TabOrder = 2
    Text = '0,00'
    OnExit = edtLimiteExit
  end
end
